### ISSUE TITLE
There may be something wrong with the test data and pre-trained models download link.

### ISSUE THREAD

**Issue by bozhenhhu** [thuxugang/opus_rota4#1]
Dear Gang Xu, 
Thanks very much for your great work. I find I cannot open the download link(https://ma-lab.rice.edu/dist/opus-rota4.zip) to download relevant data and pre-trained models. Could you update it? 
Thanks a lot.

**Comment by thuxugang** [comment]
Hi, thanks for your interests in our work.

Currently, our server at Rice university seems encounter some problems, and we will fix it ASAP. Sorry for the trouble.

Best, 
Xu Gang

**Comment by thuxugang** [comment]
Hi, we upload a copy to the Baidu Drive (https://pan.baidu.com/s/1jHRMlBkmEur9Jxwo9Ffwrg) with passwork rgzd. You can try to download it from here. :)

Best,
Xu Gang

**Comment by bozhenhhu** [comment]
Many thanks.
