### ISSUE TITLE
unavailability of test set

### ISSUE THREAD

**Issue by pgbarletta** [thuxugang/opus_rota4#3]
The first link fails and the 2nd link shows up in chinese, and for some reson google translate fails to translate it.

Also, for some reason when I click on the button that. I suppose, should let me download the file:

![image](https://github.com/thuxugang/opus_rota4/assets/5693483/45867379-940a-427a-91b7-ead73fd9e716)

I'm offered to download some `.deb` or `.rpm` package, when the file I'm interested in is a `.zip`

**Comment by thuxugang** [comment]
Hi, thanks for your interest. 

We will upload the files to GoogleDrive ASAP, sorry for the trouble.

FYI, our lastest version of side-chain modeling method OPUS-Mut and its related test sets can be found here (https://github.com/thuxugang/opus_mut), which have been uploaded to GoogleDrive.

**Comment by thuxugang** [comment]
Hi, thanks for your interest. 

We will upload the files to GoogleDrive ASAP, sorry for the trouble.

FYI, our lastest version of side-chain modeling method OPUS-Mut and its related test sets can be found here (https://github.com/thuxugang/opus_mut), which have been uploaded to GoogleDrive.

**Comment by pgbarletta** [comment]
got it. Thanks!

**Comment by pgbarletta** [comment]
got it. Thanks!
